# Use official Python image
FROM python:3.12

# Set working directory inside the container
WORKDIR /app

# Copy files from local machine to the container
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY . .

# Expose the port Flask will run on
EXPOSE 8080

# Command to run the app
CMD ["python", "app.py"]
